server:
  port: 8080

logging:
  level:
    com.emlakjet: DEBUG
#    root: DEBUG

spring:
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      fail-on-empty-beans: false
#  datasource:
#    url: jdbc:h2:mem:testdb

emlakjet:
  creditLimit: 250